name: Docker Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 레포지토리 체크아웃
      uses: actions/checkout@v4

    - name: 도커허브 로그인
      uses: docker/login-action@v3
      with:
        username: ${{ github.event.sender }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: 빌드 및 푸시
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ github.event.sender }}/${{ github.event.repository }}:latest